version: "3"
services:
  web:
    build: .
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    ports:
      - 3000:3000
volumes:
  node_modules: {}
  next: {}
